steps:
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/rag-chatbot-backend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/rag-chatbot-backend:latest',
      '.'
    ]

  # イメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rag-chatbot-backend:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rag-chatbot-backend:latest']

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'backend',
      '--image', 'gcr.io/$PROJECT_ID/rag-chatbot-backend:$BUILD_ID',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '2Gi',
      '--cpu', '2',
      '--max-instances', '10',
      '--set-env-vars', 'GEMINI_API_KEY=${_GEMINI_API_KEY}'
    ]

# ビルド成果物
images:
  - 'gcr.io/$PROJECT_ID/rag-chatbot-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/rag-chatbot-backend:latest'

# ビルドオプション
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
